### ISSUE TITLE
BUG: Unlimited ammo doesn't work with vehicules

### ISSUE THREAD

**Issue by menoanie** [aaronkirkham/jc4-console-thingy#14]
Title

**Comment by aaronkirkham** [comment]
Seems like a game "bug" as the UI shows unlimited but the weapons will still consume ammo. However, I will look into fixing this because most vehicles don't have enough ammo.

**Comment by aaronkirkham** [comment]
Fixed. Will be releasing a new version some time this week with this fix and some other new features.

Thanks.
