### ISSUE TITLE
ISSUE: Cannot get out of destroyed vehicules

### ISSUE THREAD

**Issue by menoanie** [aaronkirkham/jc4-console-thingy#16]
This is not an issue related to your program, but when a vehicule is destroyed when the player is invincible, we can't get out of it. (unlike JC3)

So I have to use the "event __reload_world" command to be able to move again.

So a patch/command to always be able to get out of a vehicule would be a nice addition.

**Comment by aaronkirkham** [comment]
Kind of related to #15 - I am currently testing an invincible vehicle feature if the player has `ply.invulnerable` enabled, which will also resolve this problem so no extra command would be necessary.

**Comment by kktos** [comment]
The trick I'm using is playing with the teleport command :) But what could be best is to be able to teleport, let's say, 1 meter above your location, therefore, outside the vehicle.

**Comment by menoanie** [comment]
> 
> 
> The trick I'm using is playing with the teleport command :) But what could be best is to be able to teleport, let's say, 1 meter above your location, therefore, outside the vehicle.

Are sure that the player would be in a "non-locked" state after using this command?
The really best way would be to do it without any commands every time.

Anyway I will close this issue since this will most likely get fixed with #15.

**Comment by kktos** [comment]
yes, I'm sure as I'm using it w/o any trouble so far :)
