### ISSUE TITLE
ISSUE: Game crashes on startup

### ISSUE THREAD

**Issue by Wurmleiche88** [aaronkirkham/jc4-console-thingy#21]
Every time i put the file in, the game just crashes on startup.

**Comment by aaronkirkham** [comment]
More info needed. What version of JC4 are you using? Latest steam version?

**Comment by Wurmleiche88** [comment]
Yeah its the Latest steam version

**Comment by Schad-Galen** [comment]
uninstall and reinstall Just Cause 4 and it should work.
