### ISSUE TITLE
REQUEST: Compatibility to Epic version

### ISSUE THREAD

**Issue by Shadow-of-N7** [aaronkirkham/jc4-console-thingy#22]
This does currently not work with the version from the Epic store. Application starts, but the menu won't show up.

**Comment by aaronkirkham** [comment]
Will download the Epic Games version today and check it out.

**Comment by boopybooperton** [comment]
Keep us posted I want to use this with some of the cool mods that require it..

**Comment by aaronkirkham** [comment]
Been checking it out today and initially it seems like the game is protected by Denuvo much more than the steam version which means I'll have to change a few things around. The binary size is also twice the size (~520mb) which makes decompiling it a pain.

Today I've been working on updating the library used in the project for hooking related things so that I can just use pattern scanning instead of hard coded addresses (which is why this currently doesn't support the Epic Store version).

Right now I have the basic stuff working in both versions (graphics drawing/input handling and some commands). I expect a working version some time this week for you guys to try out.

**Comment by Shadow-of-N7** [comment]
Thank you so much for your effort :)

**Comment by justcause4belike** [comment]
hey since i will get the console thingy for epic games version i dont have money but i really want the nukes the ones that come with the submarine so if i dont have the dlc can i still spawn the nukes with submarine or only nuke

**Comment by chickenjonte** [comment]
Yo, how is progress going with the Epic Games version?

**Comment by aaronkirkham** [comment]
Hey guys,

Please give this a try and provide feedback in this thread. This should support both latest Steam and Epic Store versions of the game.

[See below for updated version as of 22.04](https://github.com/aaronkirkham/jc4-console-thingy/issues/22#issuecomment-617953985)

**Comment by Mr-Mumbles** [comment]
Just Tested  on Epic Store version,

works flawlessly and with mods. You are the god that does the work for those of us that cant. Thankyou so much for even bothering to make this epic compatible. 

You are awesome friend :)

**Comment by chickenjonte** [comment]
You're a fucking legend for making this work so fast! Thank you!

**Comment by Frentran** [comment]
You are amazing dude. Genuinely, thank you for your effort. THANK YOU. God Bless.

**Comment by justcause4belike** [comment]
everytime i try to spawn something for example Spawn angency_cargo_missile then i press enter and it dont spawn pls help

**Comment by justcause4belike** [comment]
also when i say spawn missile it spawn a train with a big gun on it

**Comment by aaronkirkham** [comment]
> also when i say spawn missile it spawn a train with a big gun on it

The spawn system in Just Cause uses tags, they get all resources which have that tag, then spawn something random from that list, being more specific with the model names is the best way to spawn what you want. (e.g. spawn animal will be more random than spawn deer)

In your other case, `agency_cargo_missile` might be a DLC item that you don't own?

**Comment by lukerdukerpop** [comment]
i need help putting the mod in my jc4 I have epic launcher but I cant figure it out

**Comment by aaronkirkham** [comment]
Seems there was another update today, so here's another version which is working as of 22.04.

[jc4-console-thingy.v1.11.1.zip](https://github.com/aaronkirkham/jc4-console-thingy/files/4518278/jc4-console-thingy.v1.11.1.zip)

**Comment by Shadow-of-N7** [comment]
Tank you very much, it works just fine!

**Comment by Encryption12** [comment]
How do you install this?

**Comment by chickenjonte** [comment]
> How do you install this?

You just drag the xinput9_1_0.dll file into the root folder of Just Cause 4

**Comment by Encryption12** [comment]
Works great thanks

**Comment by aaronkirkham** [comment]
I'm going to close this thread now. For any new problems please open another issue.

Thanks guys.
