### ISSUE TITLE
ISSUE: Mission Nagging everytime the game is booting up

### ISSUE THREAD

**Issue by menoanie** [aaronkirkham/jc4-console-thingy#23]
I have 7 or 8 messages like this when I boot the game with the latest release.

![image](https://user-images.githubusercontent.com/58107955/80094303-4b9d9b80-8566-11ea-9d9f-698cd8e1bd11.png)

I don't know if this a bug, but removing the "notifications" would make it better.

**Comment by aaronkirkham** [comment]
Does this happen without the mod loaded? If this is part of the game then it's not something I would be interested in changing

**Comment by menoanie** [comment]
No, it does not happen with the version I build from this commit:
https://github.com/aaronkirkham/jc4-console-thingy/commit/66eafd3735a0bcbbd79eb8fe7d692d170bc1af65

**Comment by aaronkirkham** [comment]
Ok, the only thing I can think of would be to clone the latest version and comment out these 3 lines:

https://github.com/aaronkirkham/jc4-console-thingy/blob/master/src/patches.cpp#L134-L136

Those use to be behind a -quickstart argument and are maybe causing some weird side effects like this.

If you can confirm that doing that fixes this issue, then I will revert some things to make the quick loading optional again.

**Comment by menoanie** [comment]
Can you sent a build with the lines commented out?
```
Cloning into 'F:/Projects/jc4-console-thingy/deps/meow-hook'...
Host key verification failed.
fatal: Could not read from remote repository.
```

^ Getting this error while trying to clone with `--recursive` (first time I encounter this)

**Comment by aaronkirkham** [comment]
Here you go:

[jc4-console-thingy-no-quickstart.zip](https://github.com/aaronkirkham/jc4-console-thingy/files/4523580/jc4-console-thingy-no-quickstart.zip)

**Comment by menoanie** [comment]
The issue is fixed, too bad this feature was useful.

I'll use it anyway :P
