### ISSUE TITLE
Update issue

### ISSUE THREAD

**Issue by BlackShin03** [aaronkirkham/jc4-console-thingy#25]
I don't know if I am the only one with this issue, but yesterday I downloaded the update (I've got the Epic Game version) and today if I play F1 or tilde the console won't open.

**Comment by aaronkirkham** [comment]
Are you 100% sure you are using the latest (v1.11.1) version, that should support the most recent epic version which was released a few days ago.

**Comment by BlackShin03** [comment]
Actually I'm not sure. I saw a comment saying that the console wasn't working with the epic version, so i downloaded the file you linked in your reply (the comment should be from 5/6 days ago). Today I'll try the 1.11.1 and I'll let you know.

**Comment by BlackShin03** [comment]
I tried the 1.11.1 version and it is working. Thank you!

**Comment by aaronkirkham** [comment]
Good to hear!
