### ISSUE TITLE
It doesn't work at all

### ISSUE THREAD

**Issue by Louis2747** [aaronkirkham/jc4-console-thingy#26]
When i press F1 it doesn't do anything

**Comment by aaronkirkham** [comment]
Are you are using the latest (v1.11.1) version? that should support the most recent epic version which was released a few days ago.

**Comment by Louis2747** [comment]
I am very sure. And i am playing on steam

**Comment by Schad-Galen** [comment]
uninstall and reinstall Just Cause 4 worked for me

**Comment by Louis2747** [comment]
I tried that and it didn't change anything

**Comment by Louis2747** [comment]
Maybe it's because i'm playing on [manjaro kde](https://manjaro.org/) via [proton/steamplay](https://steamcommunity.com/games/221410/announcements/detail/1696055855739350561)
now that i think about it i should've said that earlier

**Comment by aaronkirkham** [comment]
I will close this issue as I can't offer any support for proton.

**Comment by Louis2747** [comment]
I got something to happen when i press F1 but there's no text and the performance is terrible
