### ISSUE TITLE
Unable to install Epic Version

### ISSUE THREAD

**Issue by boopybooperton** [aaronkirkham/jc4-console-thingy#27]
In the install instructions it says to put the **xinput9_1_0.dll** file into the game install folder but I do not see any files with those names. All I see are xinput9_1_0.h and xinput9_1_0.def in the download file. Also should I put the rest of the files in the dropzone folder?

**Comment by aaronkirkham** [comment]
Looks like you're downloading the source code zip instead of the pre-built dll.

https://github.com/aaronkirkham/jc4-console-thingy/releases/latest

Make sure you are clicking on `jc4-console-thingy.v1.11.1.zip` and none of the others.
