### ISSUE TITLE
How can I build this repository for old game version?

### ISSUE THREAD

**Issue by raghavsatyadev** [aaronkirkham/jc4-console-thingy#3]
I think I have 1.01 version of the game which is a fitgirl repack. But I am having trouble using your old build which has issues of Alt + TAB. I have already installed visual studio. Now I just want to know what I have to change so that your code can support old version also.

**Comment by parind** [comment]
@raghavsatyadev , use the old.v1.01 from releases.

**Comment by raghavsatyadev** [comment]
@parind have you totally ignored the whole issue? I have already written that I can not use that version because of Alt + TAB issue and I want to rebuild new code for the old 1.01 version and asking for the changes required to do the same.

**Comment by parind** [comment]
Are you talking about the issue, when switching, and reopening JC4, there's no response in the game, and console doesn't seem to go ? As for this issue, I think it will be fixed by the dev. And if it's something else, explain the issue.
This way it would be easier for the devs to fix it.

**Comment by raghavsatyadev** [comment]
@parind it's already fixed in the newer version, but they removed the support for old version. As I think the developer knows about this issue already

**Comment by aaronkirkham** [comment]
The `old-v1.01` branch is what you're looking for.

`git clone git@github.com:aaronkirkham/jc4-console-thingy.git`
`cd jc4-console-thingy`
`git checkout old-v1.01`

Then you can build the old version. Let me know if that helps you.

**Comment by raghavsatyadev** [comment]
I already tried that branch, but I think it contains the bug which I mentioned above

**Comment by aaronkirkham** [comment]
Hmm, ok. Can you provide a little info of what's actually happening when you alt+tab, and what you're trying todo?

As far as I know there shouldn't be any difference between the latest steam version and the v1.01 stuff which breaks that.

**Comment by raghavsatyadev** [comment]
Your mod is published here right? https://justcause4mods.com/mods/jc4-entity-spawner/

there are 3-4 comments saying that when they are using the old version 1.01, alt + tabbing between windows crashes the console means if it is opened before switching window then it just stays open all the time. 

I also experienced the same thing when I used : https://github.com/aaronkirkham/jc4-console-thingy/releases/download/v1.1/old.v1.01.zip

Link for a comment : http://disq.us/p/1y90yk6

**Comment by parind** [comment]
@aaronkirkham I can explain what happens exactly. Lets say I am in Game and using Spawner Console, leaving it enabled, if I switch between any other processes, to say, Browser, and switch back to JC4, any input isn't recorded in the console, neither the game detects any Key Press. As for this, the game needs to be restarted again, or in some cases, JC4 crashes automatically.

**Comment by aaronkirkham** [comment]
Thank you. Does that only happen in full screen mode? I tested it yesterday (using latest steam version), alt-tabbing when in windowed mode with the console input open wouldn't cause any issues and input will still be working when returning focus to the game.

EDIT: Ok, just tested in full screen mode and I can reproduce that. Will be pushing a fix very shortly. Thanks again

**Comment by aaronkirkham** [comment]
Ok. Fixed in both master & v1.01 branches. Let me know how that works for you.

https://github.com/aaronkirkham/jc4-console-thingy/releases/tag/v1.2.1

**Comment by parind** [comment]
@aaronkirkham Works great. Can close this issue. Thanks dude for pushing the fix. BTW I was halfway to implementing your JC3 fix for similar issue to this project 😆. Aaron, about the UI Improvements commit, those addresses are temp memory or in game memory ? Those addresses are causing crashes, so I guess need to adjust the addresses.

**Comment by aaronkirkham** [comment]
@parind Great. They are just hashed strings so they shouldn't cause any issues. Are you using the latest steam version? or trying to back port those commits into v1.01 branch? The latest UI manager code will not work on v1.01 version unless you update the padding alignment for the CUIManager class.

**Comment by raghavsatyadev** [comment]
Thank you @aaronkirkham & @parind I will check the fix tomorrow and tell you the final result

**Comment by parind** [comment]
Back porting them to 1.01. I am still half noob in Cpp Lang. Lol, with the 0x I thought they were addresses. Will check them later.
