### ISSUE TITLE
cannot spawn the Huntsman SAM

### ISSUE THREAD

**Issue by lukerdukerpop** [aaronkirkham/jc4-console-thingy#30]
i canto spawn the Huntsman SAM

**Comment by aaronkirkham** [comment]
Which model name are you using to try spawn it?

**Comment by lukerdukerpop** [comment]
I found out how it f I spawn in the truck that has armement its spawn connected to da truck  Sent from Mail for Windows 10 From: Aaron KSent: Saturday, May 2, 2020 7:50 AMTo: aaronkirkham/jc4-console-thingyCc: lukerdukerpop; AuthorSubject: Re: [aaronkirkham/jc4-console-thingy] cannot spawn the Huntsman SAM (#30) Which model name are you using to try spawn it?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by aaronkirkham** [comment]
> I found out how it f I spawn in the truck that has armement its spawn connected to da truck

Ok - so is this resolved? If so I will close this thread.
