### ISSUE TITLE
Just cause 4 mod not working

### ISSUE THREAD

**Issue by MonsterkillerH** [aaronkirkham/jc4-console-thingy#31]
It would seem that when i extract the xinput9_1_0.dll in the just cause 4 root file and start the epic version nothing happens when I press ~ or f1 please help.

**Comment by Encryption12** [comment]
> It would seem that when i extract the xinput9_1_0.dll in the just cause 4 root file and start the epic version nothing happens when I press ~ or f1 please help.

Looks like the games update broke the mod.

**Comment by aaronkirkham** [comment]
There doesn't appear to be any update from the Epic Store. Latest version is still `JC4_1830880_1830540` which is support by v1.12.

Double check your version by clicking on the ellipsis (...) in your Epic Games Library under Just Cause 4.

**Comment by MonsterkillerH** [comment]
yeah it says its the same version

**Comment by aaronkirkham** [comment]
Unsure as to what could be causing this right now. Please give this a try:

[jc4-console-thingy-debug-log.zip](https://github.com/aaronkirkham/jc4-console-thingy/files/4577658/jc4-console-thingy-debug-log.zip)

After you start your game, go to your jc4 folder (where xinput9_1_0.dll is located) and paste the contents of `xinput9_1_0.log` into a reply here.

**Comment by MonsterkillerH** [comment]
Do I skip the file or do I replace it because they both have the same name

**Comment by aaronkirkham** [comment]
Replace the DLL which is already in your JC4 folder. (should be xinput9_1_0.dll)

**Comment by Encryption12** [comment]
That works well, thanks
