### ISSUE TITLE
Is there a way to have this work with the Main Menu?

### ISSUE THREAD

**Issue by Alt-F-4** [aaronkirkham/jc4-console-thingy#32]
With this mod installed I am forced into the game, unable to engage in the first mission's cutscenes and bugs the game's story, is there a way to fix this and make it so I can actually use the main menu?

**Comment by aaronkirkham** [comment]
Hey, please give the latest version a try. This will disable the forced quick-start stuff and should fix your problems. Let me know if it works for you. Thanks

https://github.com/aaronkirkham/jc4-console-thingy/releases/latest

**Comment by Alt-F-4** [comment]
It does work indeed, thanks!
