### ISSUE TITLE
console no work

### ISSUE THREAD

**Issue by Tomperyeeter** [aaronkirkham/jc4-console-thingy#35]
hey the plugin 

https://github.com/aaronkirkham/jc4-console-thingy/releases/tag/v1.12.1

does not work i press the f1 key or tilde nothing happens ? 
im using the cracked version of the game btw

**Comment by aaronkirkham** [comment]
None of the latest versions will work without the steam version.

You could try https://github.com/aaronkirkham/jc4-console-thingy/releases/tag/v1.2.1 and download the `old-v1.01.zip` file.
