### ISSUE TITLE
Pressing F1 and tilde key and console not opening.

### ISSUE THREAD

**Issue by migbe95** [aaronkirkham/jc4-console-thingy#38]
Hi, I have tried installing this mod several times but the console never opens ingame, no matter how many times I press F1 or tilde key. Is it because My game is cracked? I saw a youtube video of someone being able to use this mod in the same cracked version as me. The one by CPY. Could you help me?

**Comment by migbe95** [comment]
I mean, if it is because my game is cracked, I dont mind buying it but I don’t want to buy the game and have the same issue hahaha.

**Comment by aaronkirkham** [comment]
Current versions only work with legit Steam copies!
