### ISSUE TITLE
Console not opening in Epic Games latest version

### ISSUE THREAD

**Issue by JoeSnuffie** [aaronkirkham/jc4-console-thingy#44]
Epic Games reports my version as JC4_2226912_1830540 and the .exe is just showing 1.0 with a size of 444,172kb. I'm happy to provide any other info.

I uninstalled the game maybe a year ago and it was working then. I reinstalled a backup from 2020, copied over the .etstore folder and it runs, but the console still doesn't open when typing ~ or F1. Any ideas? I've completed the game and now I really enjoy just messing around and blowing things up from time to time.

**Comment by aaronkirkham** [comment]
Hi

If you can upload the .exe and provide a link to me I can take a look.

**Comment by JoeSnuffie** [comment]
Thanks for the fast reply. I know this is just an older game but I really appreciate you willing to look at it.
https://drive.google.com/file/d/10HMGYUhsXa3atGjOMe_9Krr0Wq25tA0-/view?usp=sharing

Thank you,
Jeff

**Comment by aaronkirkham** [comment]
Hey, thanks for that, looks like it's definitely a different version.

If you want to give [jc4-console-thingy.v1.13.zip](https://github.com/aaronkirkham/jc4-console-thingy/files/8572674/jc4-console-thingy.v1.13.zip) a try and report back letting me know if that's working for you?

Thanks!

**Comment by JoeSnuffie** [comment]
Wow that was fast. It’s working again!

Thank you so much.
