### ISSUE TITLE
Steam Deck: poor performance and no text

### ISSUE THREAD

**Issue by MilesCourtie** [aaronkirkham/jc4-console-thingy#50]
Hi, I've been trying this mod on a Steam Deck and have come across two issues that I haven't experienced on Windows.

The first issue is that when the mod is active the game drops to about 6FPS, compared to 40+FPS without the mod. This is constant from the moment the game starts (i.e. before the world is loaded) and continues even when the game is paused.

The second issue is that the console's text isn't visible, though the translucent background does still appear.

Aside from these problems all other aspects of the mod work perfectly as far as I can tell.

I'm running the Steam version of Just Cause 4 with Proton 7.0-4 (the default recommended by Valve) on a 512GB Steam Deck.

To tell Proton/WINE to load the DLL I'm using the following launch options in Steam:
`WINEDLLOVERRIDES='xinput9_1_0.dll=n,b' %command%`

I've tried both with and without the `-quickstart` option, the poor performance and missing text are the same in both cases.

Many thanks for your time and for this excellent mod.

**Comment by JLyne** [comment]
The poor performance appears to be caused by proton continuously loading and unloading d3dcompiler_47.dll, for whatever reason. Running `protontricks 517630 d3dcompiler_47` to use the native version of the dll resolves this.

I do not have the text issue described here, so perhaps this fixes both issues.

**Comment by MilesCourtie** [comment]
This fixed both issues for me - thanks very much!
